"""initial: missions, positions, price_quotes

Revision ID: 0001
Revises: 
Create Date: 2026-05-31 00:52:11.315725
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('budget_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_positions', sa.SmallInteger(), nullable=False),
    sa.Column('max_position_pct', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('horizon_months', sa.SmallInteger(), nullable=False),
    sa.Column('sectors_excluded', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('allow_shorts', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='mission_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('decomposition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assessments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shortlist_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ta_outputs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('memos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('portfolio_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_missions_created_at', 'missions', ['created_at'], unique=False)
    op.create_index('ix_missions_status_created_at', 'missions', ['status', 'created_at'], unique=False)
    op.create_table('price_quotes',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('notional_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('entry_price_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_ticker', 'positions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_ticker', table_name='positions')
    op.drop_table('positions')
    op.drop_table('price_quotes')
    op.drop_index('ix_missions_status_created_at', table_name='missions')
    op.drop_index('ix_missions_created_at', table_name='missions')
    op.drop_table('missions')
    op.execute("DROP TYPE IF EXISTS mission_status")
    # ### end Alembic commands ###
